config/routes.rb
Rails.application.routes.draw do
  root to: "calendars#index"
  resource :calendars, only: [:index, :new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/calendar.rb
class Calendar < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/calendars_controller.rb
class CalendarsController < ApplicationController
  def index
    @calendars = Calendar.order(id: :asc)
  end

  def new
    @calendar = Calendar.new
  end

  def create
    # binding.pry
    # save_params = params[:calendar][:date].split(" ").map(&:to_date)
    save_params = params[:calendar][:date].to_date
    Calendar.create!(date: save_params)
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/calendars/create.html.erb
<h1>Calendars#create</h1>
<p>Find me in app/views/calendars/create.html.erb</p>

app/views/calendars/index.html.erb
<%= link_to "日付投稿ページへ", new_calendars_path, class: "btn btn-block btn-primary w-50 mx-auto my-3" %>
<h1 class="text-center">日付一覧</h1>
<table class="table table-bordered table-striped mt-4 w-50 mx-auto text-center">
  <thead class="table-primary">
    <tr>
      <th scope="col">No.</th>
      <th scope="col" class="w-100">日付</th>
    </tr>
  </thead>
  <tbody>
    <% @calendars.each.with_index(1) do |calendar, i| %>
      <tr>
        <th scope="row" class="text-right"><%= i %></th>
        <td class="break-word"><%= calendar.date %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/calendars/new.html.erb
<div class ="calendar mb-3">
  <%= form_with model: @calendar do |form| %>
    <input id ="edit_calendar" type="text" name="calendar[date]" readonly="readonly" >
    <%= form.submit "送信", class: "btn btn-block btn-primary mt-3" %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CalendarSample2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'calendar', 'data-turbolinks-track': 'reload' if controller_name == 'calendars' %>
  </head>
  <body>
    <%= yield %>
  </body>
</html>